### ISSUE TITLE
Luban laser process does process to SVG wrongly

### ISSUE THREAD

**Issue by pauserratgutierrez** [Snapmaker/Luban#786] opened 2021-02-22 13:46 UTC
I have done a svg with illustrator. When importedto the luban edit software everything's correct. Once I click process, the svg is displayed wrongly and some parts dissapear.

Uploading svg:
![svg edit](https://user-images.githubusercontent.com/73240206/108716616-a43e1c00-751c-11eb-8138-42cfa5e54740.jpg)
The svg once we process it (wrongly):
![svg process](https://user-images.githubusercontent.com/73240206/108716623-a6a07600-751c-11eb-9362-1abaf4e8b3a7.jpg)

**Comment by jane-rose** [comment] 2021-04-08 04:18
Known  bug, it will be fixed on version v3.15.0.

**Comment by awesomeruss** [comment] 2021-05-04 07:00
I think I have the same issue with 3.15.0. SVG is pretty simple with no groups. Everything is fine until I click 'Preview' at which point horizontal size scales up. 
![Broken preview screenshot 1](https://user-images.githubusercontent.com/48243754/116969800-c687af00-acae-11eb-80d4-5149a85dc18b.png)
![Broken preview screenshot 2](https://user-images.githubusercontent.com/48243754/116969808-cb4c6300-acae-11eb-8e67-77fee09115f3.png)
![Broken preview screenshot 3](https://user-images.githubusercontent.com/48243754/116969814-cedfea00-acae-11eb-8f81-f33e7bf89c91.png)

**Comment by jane-rose** [comment] 2021-05-07 01:52
@awesomeruss Ok, could u send us the project file or svg file to see what happened on these file?

**Comment by jane-rose** [comment] 2021-05-07 01:55
@paauserrat Is this problem solved on v3.15.0? If not, you can send us the svg file too.

**Comment by awesomeruss** [comment] 2021-05-09 16:07
> @paauserrat Is this problem solved on v3.15.0? If not, you can send us the svg file too.

Never mind - I found the problem. My SVG was at fault - the width and height were the wrong way round(!)

**Comment by Galindorf** [comment] 2021-05-10 03:29
I also just had this issue. I have created a grid pattern to test my X axis by making long rectangles. Luban will only path half of them, and they are misaligned also! 

![image](https://user-images.githubusercontent.com/17105217/117602302-f18e5a80-b115-11eb-9247-97f1ea3f25c7.png)
![image](https://user-images.githubusercontent.com/17105217/117602315-f81cd200-b115-11eb-9b13-0ef314e27aa2.png)

**Comment by Galindorf** [comment] 2021-05-10 03:50
Note: I converted the paths from "rectangles" to "Curves" (CorelDraw X8) and then used "Combine" to make them a single curve, then saved as SVG. They showed up and engraved properly after that.

**Comment by sumibin** [comment] 2023-03-21 11:27
Given that there is no available file in the feedback, I can't confirm if the problem is fixed. If the problem persists in the new version please reopen it.

**Closed by sumibin** 2023-03-21 11:27 UTC
Labels: Type: Bug/Bug Fix
