### ISSUE TITLE
Bug: 4.5.0 Machine Settings can not save 10W Laser option, app restarts

### ISSUE THREAD

**Issue by darienm** [Snapmaker/Luban#1876] opened 2023-01-12 16:22 UTC
### Affected Version(s)
4.5.0

### Is this a regression? (optional)
Yes, 4.4.0 allowed selecting the 10W laser

1. Open Machine Settings panel from Settings or Snapmaker Luban menu
2. Change Laser Module from 1600mW Laser to 10W Laser
3. Click Save
4. All work is lost and app restarts as if just launched, still on the previous laser setting

Expected behavior:
Accept the setting change, continue working

Platform:
- Operating System: macOS Ventura
- Printer: Snapmaker A350

![cap_2914](https://user-images.githubusercontent.com/2875381/212122277-3fc82239-c7b8-4e70-93ae-03a0112b301c.png)

**Comment by sumibin** [comment] 2023-01-13 15:24
We confirmed the problem. In this case the Laser Gcode generator will still be a 10W laser.

**Comment by rocksolid99** [comment] 2023-01-14 19:18
> We confirmed the problem. In this case the Laser Gcode generator will still be a 10W laser.

Please confirm this because I was cutting 5 sheets of 2mm EVA foam like a hot knife through butter just a few days before this update and now it's not even cutting the top sheet on the same exact settings. I suspect it is outputting 1.6W and not 10W. I have laser power set to 100%. The focal of the laser itself even looks different.

**Comment by parachvte** [comment] 2023-01-18 17:15
It's been fixed in https://github.com/Snapmaker/Luban/pull/1889

**Closed** 2023-01-31 03:18 UTC
Labels: Type: Bug/Bug Fix, Category: UX
