### ISSUE TITLE
.svg Files imported from InkScape have the wrong size.

### ISSUE THREAD

**Issue by Pflugshaupt** [Snapmaker/Luban#502] opened 2020-10-25 16:52 UTC
Since version 3.9.0 and also in the 3.10.0 alpha, svg files using mm units coming from InkScape get much too small (about 4x) when loaded into Luban to laser cut. It was fine in 3.8.0.

**Comment by thisismlh** [comment] 2020-11-09 21:04
Same is true for Adobe Illustrator

**Comment by t-foster** [comment] 2020-11-15 14:37
Same with svg files exported from openscad.

openscad code:

    square([200,40]);


then render and export to svg produces the following svg xml
```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="200mm" height="40mm" viewBox="0 -40 200 40" xmlns="http://www.w3.org/2000/svg" version="1.1">
<title>OpenSCAD Model</title>
<path d="
M 0,-0 L 200,-0 L 200,-40 L 0,-40 z
" stroke="black" fill="lightgray" stroke-width="0.5"/>
</svg>
```

Then when it gets imported into Luban cnc and laser it ends up being 25.6 mm wide and 5.1 mm tall.  Maybe the SVGs are just getting bound down to 1 inch at the greatest distance?

**Comment by t-foster** [comment] 2020-11-15 15:00
Although as a user I can then just peek at the first few lines of the svg xml and take the width/height values and after adding to luban manually set the size of my drawn object.  IDK if illustrator or inkscape have those xml fields in them but it may be worth checking.

**Comment by Pflugshaupt** [comment] 2020-11-15 17:08
Of course they have them. This is just a silly bug in the svg importer - hope it gets fixed soon.

**Comment by t-foster** [comment] 2020-11-18 00:29
Sometimes you need to spoon-feed a developer a test case and what you expect for a result so they can put that into some sort of unit test to make more resilient code.

**Comment by srfin** [comment] 2020-12-02 15:50
It appears that all laser file imports are too small? I just opened the "Laser cut gift box" test project on 3.12.3 and it was only 25.6x25.6mm. I also imported a dxf I had created myself and it was also much too small.

**Comment by srfin** [comment] 2020-12-02 16:54
I just did some testing of old versions and found that 3.8 is the last version which correctly loads the gift box project. Unfortunately that isn't able to correctly load DXF files from Fusion 360.

Looks like I'll just give up on laser cutting precise dimensions until this is fixed.

**Comment by Pflugshaupt** [comment] 2020-12-02 19:52
Indeed.. using 3.8. because of that  which annoyingly cannot store 3d print custom profiles :(

**Comment by jane-rose** [comment] 2020-12-03 04:11
@Pflugshaupt  Is it occurs in v3.12.2? For storing 3d print custom profiles, this feature should be available in version 3.12.2

**Comment by Pflugshaupt** [comment] 2020-12-03 06:45
profiles is fine since 3.9, but I need laser cuts that have the right size so I never went past 3.8. I am waiting for this issue here #502 to be fixed.

**Comment by patchrocks** [comment] 2020-12-09 12:31
I just ran into the same (or similar) issue: I use FreeCAD 0.19 and Luban 3.12.3. When creating a SVG or DXF, the model is smaller when importing in Snapmaker Luban (a circle with 20 mm diameter results in a circle with 2,8 mm in Luban). Is this planned to be fixed in a future version, or is there any workaround - or something I do wrong? Thanks a lot!

**Comment by patchrocks** [comment] 2020-12-11 14:05
Additional information: I can confirm that version 3.8 works as expected. Scale is correct when I load the SVG from FreeCAD in Luban 3.8.

**Comment by dwienie** [comment] 2020-12-29 12:04
I installed 3.13.0 and I have also an issue importing svg file in luban.  It is to small but indeed you can resize but the bigger problem is that luban adds a whitespace around the object even if the source svg file has zero margin.   This gives issues in resizing.   you can not scale it to a size that is exactly the size of the source because of that margin.    I tried with DXF, SVG and PNG (in Vector mode) all of them have a margin around the object.  Please fix this otherwise we can not cut  precise based on the source object.

**Comment by Vincent-Noben** [comment] 2020-12-29 19:48
Some tests with inkscape en illustrator.
Weird thing is that it does look normal in "Process" mode, but bad in Edit mode. (I set width to 200mm)
I currently cannot test it but now I wonder if it is only a visual bug of the edit mode, or if the actual lasered result is also to small.

https://github.com/Snapmaker/Luban/issues/502
![image](https://user-images.githubusercontent.com/5732198/103310109-1e6b8c00-4a17-11eb-91d3-35937d52c26d.png)

**Comment by parachvte** [comment] 2020-12-30 02:49
It's a bug introduced in v3.9.0, we are still refactor the SVG editor to fix it.
You can trust the "Process" result rather than in "Edit".

**Comment by Galindorf** [comment] 2021-01-31 19:17
Can confirm, Luban 3.13.1 importing .SVG for laser cutting, files saved in CorelDraw. Imports the entire file about an inch in size. I'm glad to know this is a bug, I am a brand new user and I thought this was a terrible program!

**Comment by Pflugshaupt** [comment] 2021-01-31 19:35
Seeing that I reported this bug in October and it is still not fixed does make me feel it is a terrible program :(. It is easily the weakest point of the whole snapmaker package. The slicer is missing so many (cura) features, the cnc part is mostly a joke and lasering is crippled by this very bug that feels like it could be fixed in a few hours.

I wished they would just abort this project and instead provide first class support for Cura/Fusion 360 and some laser engraving software. Luban wants to do too many things at the same time and fails at all of them in some way.

**Comment by srfin** [comment] 2021-02-01 15:52
I think its pretty clear that Snapmaker doesn't have the resources to give software the attention it needs either on Luban or the firmware. The pace of development is very slow even for important bug fixes like this. It would be great if they would partner with 3rd parties to provide licenses/support for other programs.

I'm really interested in the rotary module, but I can't see how they're going to provide the software needed to use it well. I'm definitely not interested in paying full price to get 4-axis support in Fusion 360 for example.

**Comment by marsiancba** [comment] 2021-02-04 09:01
Around 1 month ago I have submitted a pull request for this:

https://github.com/Snapmaker/Luban/pull/681

Not sure why it is not merged/fixed already - it is just 1 line change.

**Comment by t-foster** [comment] 2021-02-04 15:13
> Not sure why it is not merged/fixed already - it is just 1 line change.

I'm not one of their programmers and haven't explored their source code enough to tell if it is set up for unit testing, but speaking as a programmer in general I wouldn't take a one line change without unit tests for that area which break without the change and pass with it.

**Comment by parachvte** [comment] 2021-03-01 09:27
Updates on PR #681:

We have #773 and #778 pull requests to solve this issue, they were merged and will be released with v3.15.0.

While there are still several bugs regarding the SVG editor, we are working on them currently.
I'll keep this issue open until release of v3.15 (about April 6th).

**Comment by Mortisaga** [comment] 2021-03-12 20:03
I don't know if it is the same issue I have or at least related:
when adding files to Luban that I made with inkscape, not only it appears way to small but when I resize it to my original size it will have a strange border around... (see pic)
![grafik](https://user-images.githubusercontent.com/79230540/110992294-0482e980-8376-11eb-8b74-753a3df6c879.png)

the original vector is 107 mm in height, but in Luban it sizes the border to 107 and my object is way too small...
I tested this with 3.13.1 as well as 3.14.0 alpha 14 - same problem
I found this very problem with .dfx, .svg, .png files (tested no others)

**Comment by parachvte** [comment] 2021-04-27 09:08
Please check if the issue still occurs in v3.15.0.

I'm closing this issue for now.

**Closed by parachvte** 2021-04-27 09:08 UTC
Labels: Category: Editor, Priority: High, State: Follow Up

**Comment by hotchips** [comment] 2021-10-31 13:57
Was having same issue - Worked when I loaded original SVG into illustrator and re-saved with SVG 1.0 spec

**Comment by faberc** [comment] 2023-12-17 03:57
This problem exists in Luban 4.10.1

**Comment by LMalyurek** [comment] 2023-12-23 18:55
Confirm with faberc.  Scale still not coming in correctly with 4.10.1.  Please put some effort into this, accuracy matters to almost everything I want to do on this machine.  I am honestly amazed that this has been apparently broken for so long....

**Comment by Juntrimp** [comment] 2024-03-27 05:47
Still an issue in 4.11.0
